# Generated by Django 4.2.3 on 2023-09-29 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('ชาย', 'ชาย'), ('หญิง', 'หญิง')], max_length=5)),
                ('birthdate', models.DateField(default=None)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=10)),
                ('profile1', models.ImageField(upload_to='profile_customers/')),
                ('profile2', models.ImageField(upload_to='profile_customers/')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_th', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('ชาย', 'ชาย'), ('หญิง', 'หญิง')], max_length=5)),
                ('birthdate', models.DateField(default=None)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=10)),
                ('profile1', models.ImageField(upload_to='profile_employees/')),
                ('profile2', models.ImageField(upload_to='profile_employees/')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Geographies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subdistrict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.IntegerField()),
                ('name_th', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.district')),
            ],
        ),
        migrations.CreateModel(
            name='Provinces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_th', models.CharField(max_length=255)),
                ('name_th_short', models.CharField(max_length=10)),
                ('name_en', models.CharField(max_length=255)),
                ('geographies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.geographies')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='provinces',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.provinces'),
        ),
    ]
