# Generated by Django 4.2.3 on 2023-09-29 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('1', '1 เดือน'), ('2', '2 เดือน'), ('3', '3 เดือน'), ('4', '4 เดือน'), ('5', '5 เดือน'), ('6', '6 เดือน')], max_length=255)),
                ('picture', models.ImageField(upload_to='contracts/')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_weight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_interest', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_loan', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('contract_status', models.BooleanField(default=False)),
                ('redemption_status', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.customer')),
                ('employee', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('due_date', models.DateField(null=True)),
                ('monthly_installments', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monthly_interest', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monthly_payment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remaining_principal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('picture', models.ImageField(blank=True, upload_to='Payments/')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.contract')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.contract')),
            ],
        ),
    ]
