# Generated by Django 4.2.3 on 2023-09-04 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('gold_type', models.CharField(max_length=255)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('period', models.CharField(choices=[('1', '1 เดือน'), ('2', '2 เดือน'), ('3', '3 เดือน'), ('4', '4 เดือน'), ('5', '5 เดือน'), ('6', '6 เดือน')], max_length=255)),
                ('picture', models.ImageField(blank=True, upload_to='contract/')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.customer')),
            ],
        ),
    ]
