# Generated by Django 4.2.3 on 2023-09-29 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repayment',
            name='picture',
            field=models.ImageField(upload_to='Payments/'),
        ),
    ]
