# Generated by Django 4.2.3 on 2023-09-05 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_contractitem_rename_gold_type_contract_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='period',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='picture',
        ),
    ]
