# Generated by Django 4.2.3 on 2023-10-01 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='netTotal',
            new_name='net_total',
        ),
    ]
